from .nodes import NODE_CLASS_MAPPINGS as NODES, NODE_DISPLAY_NAME_MAPPINGS as NAMES
from .extra_nodes import NODE_CLASS_MAPPINGS as EXTRA_NODES, NODE_DISPLAY_NAME_MAPPINGS as EXTRA_NAMES

NODE_CLASS_MAPPINGS = {**NODES, **EXTRA_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**NAMES, **EXTRA_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
